//! PDF document (PdfWriter) rows: documents, pages, signatures. Pool-only.

use kubuno_db::{new_id, params, DbPool};
use serde_json::Value;
use uuid::Uuid;

use crate::errors::{PaintsharpError, Result};
use crate::models::pdf::{
    PdfDocument, PdfDocumentSummary, PdfPage, PdfPageSummary, PdfSignature,
};

const SUMMARY_COLS: &str =
    "id, owner_id, title, page_count, thumbnail_path, is_starred, updated_at, created_at";

const DOC_COLS: &str = "id, owner_id, title, source_path, page_count, thumbnail_path, settings, \
                        file_id, is_starred, is_trashed, trashed_at, last_edited_by, \
                        created_at, updated_at";

// ── Documents ─────────────────────────────────────────────────────────────────

pub async fn list_documents(
    db: &DbPool,
    owner: Uuid,
    starred: bool,
    trashed: bool,
    limit: i64,
    offset: i64,
) -> Result<Vec<PdfDocumentSummary>> {
    let sql = if starred {
        format!(
            "SELECT {SUMMARY_COLS} FROM paintsharp.pdf_documents
             WHERE owner_id = $1 AND is_starred = TRUE AND is_trashed = FALSE
             ORDER BY updated_at DESC LIMIT $2 OFFSET $3"
        )
    } else if trashed {
        format!(
            "SELECT {SUMMARY_COLS} FROM paintsharp.pdf_documents
             WHERE owner_id = $1 AND is_trashed = TRUE
             ORDER BY trashed_at DESC LIMIT $2 OFFSET $3"
        )
    } else {
        format!(
            "SELECT {SUMMARY_COLS} FROM paintsharp.pdf_documents
             WHERE owner_id = $1 AND is_trashed = FALSE
             ORDER BY updated_at DESC LIMIT $2 OFFSET $3"
        )
    };
    Ok(db.fetch_all_as::<PdfDocumentSummary>(&sql, params![owner, limit, offset]).await?)
}

/// Creates a document plus `page_count` blank pages atomically. Returns
/// `(doc_id, page_ids)`, the page ids ordered from page 1.
pub async fn create_document(
    db: &DbPool,
    owner: Uuid,
    title: &str,
    page_count: i32,
    width: f64,
    height: f64,
) -> Result<(Uuid, Vec<Uuid>)> {
    let doc_id = new_id();
    let mut tx = db.begin().await?;
    tx.execute(
        "INSERT INTO paintsharp.pdf_documents (id, owner_id, title, page_count)
         VALUES ($1, $2, $3, $4)",
        params![doc_id, owner, title, page_count],
    )
    .await?;
    let mut page_ids = Vec::with_capacity(page_count.max(0) as usize);
    for n in 1..=page_count {
        let page_id = new_id();
        tx.execute(
            "INSERT INTO paintsharp.pdf_pages (id, document_id, page_number, width, height)
             VALUES ($1, $2, $3, $4, $5)",
            params![page_id, doc_id, n, width, height],
        )
        .await?;
        page_ids.push(page_id);
    }
    tx.commit().await?;
    Ok((doc_id, page_ids))
}

/// Insert used by duplicate (metadata only; pages inserted separately).
pub async fn create_document_meta(
    db: &DbPool,
    owner: Uuid,
    title: &str,
    page_count: i32,
    settings: &Value,
) -> Result<Uuid> {
    let id = new_id();
    db.execute(
        "INSERT INTO paintsharp.pdf_documents (id, owner_id, title, page_count, settings)
         VALUES ($1, $2, $3, $4, $5)",
        params![id, owner, title, page_count, settings.clone()],
    )
    .await?;
    Ok(id)
}

/// Writes the imported document row and its pages in one transaction. `doc_id`
/// is generated by the caller (it names the stored source file too).
#[allow(clippy::too_many_arguments)]
pub async fn import_document(
    db: &DbPool,
    doc_id: Uuid,
    owner: Uuid,
    title: &str,
    source_path: &str,
    page_count: i32,
    source_file_id: Option<Uuid>,
    pages_meta: &[(f64, f64)],
) -> Result<Vec<Uuid>> {
    let mut tx = db.begin().await?;
    tx.execute(
        "INSERT INTO paintsharp.pdf_documents
            (id, owner_id, title, source_path, page_count, source_file_id)
         VALUES ($1, $2, $3, $4, $5, $6)",
        params![doc_id, owner, title, source_path, page_count, source_file_id],
    )
    .await?;

    let mut page_ids = Vec::with_capacity(pages_meta.len());
    for (n, (w, h)) in pages_meta.iter().enumerate() {
        let page_id = new_id();
        tx.execute(
            "INSERT INTO paintsharp.pdf_pages (id, document_id, page_number, width, height, source_index)
             VALUES ($1, $2, $3, $4, $5, $6)",
            params![page_id, doc_id, (n + 1) as i32, *w, *h, n as i32],
        )
        .await?;
        page_ids.push(page_id);
    }
    tx.commit().await?;
    Ok(page_ids)
}

pub async fn set_file_id(db: &DbPool, id: Uuid, file_id: Uuid) -> Result<()> {
    db.execute(
        "UPDATE paintsharp.pdf_documents SET file_id = $1 WHERE id = $2",
        params![file_id, id],
    )
    .await?;
    Ok(())
}

pub async fn get_document(db: &DbPool, id: Uuid, owner: Uuid) -> Result<Option<PdfDocument>> {
    Ok(db
        .fetch_optional_as::<PdfDocument>(
            "SELECT * FROM paintsharp.pdf_documents WHERE id = $1 AND owner_id = $2",
            params![id, owner],
        )
        .await?)
}

pub async fn get_active_document(db: &DbPool, id: Uuid, owner: Uuid) -> Result<Option<PdfDocument>> {
    let sql = format!(
        "SELECT {DOC_COLS} FROM paintsharp.pdf_documents
         WHERE id = $1 AND owner_id = $2 AND is_trashed = FALSE"
    );
    Ok(db.fetch_optional_as::<PdfDocument>(&sql, params![id, owner]).await?)
}

pub async fn rename_document(db: &DbPool, id: Uuid, title: &str) -> Result<()> {
    db.execute(
        "UPDATE paintsharp.pdf_documents SET title = $1 WHERE id = $2",
        params![title, id],
    )
    .await?;
    Ok(())
}

pub async fn update_document(
    db: &DbPool,
    id: Uuid,
    owner: Uuid,
    title: Option<&str>,
    thumbnail_path: Option<&str>,
    is_starred: Option<bool>,
    settings: Option<&Value>,
) -> Result<u64> {
    Ok(db
        .execute(
            "UPDATE paintsharp.pdf_documents SET
                title          = COALESCE($1, title),
                thumbnail_path = COALESCE($2, thumbnail_path),
                is_starred     = COALESCE($3, is_starred),
                settings       = COALESCE($4, settings),
                last_edited_by = $5
             WHERE id = $6 AND owner_id = $7",
            params![
                title,
                thumbnail_path,
                is_starred,
                settings.cloned(),
                owner,
                id,
                owner
            ],
        )
        .await?)
}

pub async fn exists(db: &DbPool, id: Uuid, owner: Uuid) -> Result<bool> {
    Ok(db
        .fetch_optional_scalar::<Uuid>(
            "SELECT id FROM paintsharp.pdf_documents WHERE id = $1 AND owner_id = $2 LIMIT 1",
            params![id, owner],
        )
        .await?
        .is_some())
}

/// Whether a live (non-trashed) document is owned by `owner`.
pub async fn check_owner(db: &DbPool, id: Uuid, owner: Uuid) -> Result<bool> {
    Ok(db
        .fetch_optional_scalar::<Uuid>(
            "SELECT id FROM paintsharp.pdf_documents
             WHERE id = $1 AND owner_id = $2 AND is_trashed = FALSE LIMIT 1",
            params![id, owner],
        )
        .await?
        .is_some())
}

pub async fn doc_file_id(db: &DbPool, id: Uuid, owner: Uuid) -> Result<Uuid> {
    let fid: Option<Uuid> = db
        .fetch_optional_scalar::<Uuid>(
            "SELECT file_id FROM paintsharp.pdf_documents WHERE id = $1 AND owner_id = $2",
            params![id, owner],
        )
        .await?;
    if let Some(f) = fid {
        return Ok(f);
    }
    if exists(db, id, owner).await? {
        Err(PaintsharpError::NotFound(format!("Contenu du document {id}")))
    } else {
        Err(PaintsharpError::NotFound(id.to_string()))
    }
}

/// Marks the document edited (bumps last_edited_by).
pub async fn touch_document(db: &DbPool, id: Uuid, owner: Uuid) -> Result<()> {
    db.execute(
        "UPDATE paintsharp.pdf_documents SET last_edited_by = $1 WHERE id = $2",
        params![owner, id],
    )
    .await?;
    Ok(())
}

pub async fn trash_document(db: &DbPool, id: Uuid, owner: Uuid) -> Result<u64> {
    Ok(db
        .execute(
            "UPDATE paintsharp.pdf_documents SET is_trashed = TRUE, trashed_at = $1
             WHERE id = $2 AND owner_id = $3 AND is_trashed = FALSE",
            params![chrono::Utc::now(), id, owner],
        )
        .await?)
}

pub async fn restore_document(db: &DbPool, id: Uuid, owner: Uuid) -> Result<()> {
    db.execute(
        "UPDATE paintsharp.pdf_documents SET is_trashed = FALSE, trashed_at = NULL
         WHERE id = $1 AND owner_id = $2",
        params![id, owner],
    )
    .await?;
    Ok(())
}

/// Deletes a trashed document and returns `(source_path, file_id)`.
/// `Ok(None)` means no trashed document matched.
pub async fn delete_document(
    db: &DbPool,
    id: Uuid,
    owner: Uuid,
) -> Result<Option<(Option<String>, Option<Uuid>)>> {
    let del = "DELETE FROM paintsharp.pdf_documents
               WHERE id = $1 AND owner_id = $2 AND is_trashed = TRUE";
    let sel = "SELECT source_path, file_id FROM paintsharp.pdf_documents
               WHERE id = $1 AND owner_id = $2 AND is_trashed = TRUE";
    let mut tx = db.begin().await?;
    let row = kubuno_db::returning::delete_returning_row(
        &mut tx,
        del,
        params![id, owner],
        "source_path, file_id",
        sel,
        params![id, owner],
    )
    .await?;
    let out = match row {
        Some(r) => Some((r.try_get::<Option<String>>("source_path")?, r.try_get::<Option<Uuid>>("file_id")?)),
        None => None,
    };
    tx.commit().await?;
    Ok(out)
}

/// `source_path` + `title`, for serving the imported source PDF.
pub async fn source_of(db: &DbPool, id: Uuid, owner: Uuid) -> Result<Option<(Option<String>, String)>> {
    let row = db
        .fetch_optional_row(
            "SELECT source_path, title FROM paintsharp.pdf_documents
             WHERE id = $1 AND owner_id = $2",
            params![id, owner],
        )
        .await?;
    match row {
        Some(r) => Ok(Some((r.try_get::<Option<String>>("source_path")?, r.try_get::<String>("title")?))),
        None => Ok(None),
    }
}

/// open_by_file: an already-known document for this Drive file — either the
/// native `.kbpdf` (`file_id`) or a raw PDF already imported (`source_file_id`).
pub async fn find_for_file(db: &DbPool, file_id: Uuid, owner: Uuid) -> Result<Option<Uuid>> {
    Ok(db
        .fetch_optional_scalar::<Uuid>(
            "SELECT id FROM paintsharp.pdf_documents
             WHERE owner_id = $1 AND is_trashed = FALSE AND (file_id = $2 OR source_file_id = $3)",
            params![owner, file_id, file_id],
        )
        .await?)
}

// ── Pages ─────────────────────────────────────────────────────────────────────

pub async fn list_page_summaries(db: &DbPool, doc_id: Uuid) -> Result<Vec<PdfPageSummary>> {
    Ok(db
        .fetch_all_as::<PdfPageSummary>(
            "SELECT id, page_number, width, height, rotation, source_index
             FROM paintsharp.pdf_pages WHERE document_id = $1 ORDER BY page_number",
            params![doc_id],
        )
        .await?)
}

pub async fn list_pages(db: &DbPool, doc_id: Uuid) -> Result<Vec<PdfPage>> {
    Ok(db
        .fetch_all_as::<PdfPage>(
            "SELECT * FROM paintsharp.pdf_pages WHERE document_id = $1 ORDER BY page_number",
            params![doc_id],
        )
        .await?)
}

pub async fn get_page(db: &DbPool, doc_id: Uuid, page_num: i32) -> Result<Option<PdfPage>> {
    Ok(db
        .fetch_optional_as::<PdfPage>(
            "SELECT * FROM paintsharp.pdf_pages WHERE document_id = $1 AND page_number = $2",
            params![doc_id, page_num],
        )
        .await?)
}

pub async fn page_id_for(db: &DbPool, doc_id: Uuid, page_num: i32) -> Result<Option<Uuid>> {
    Ok(db
        .fetch_optional_scalar::<Uuid>(
            "SELECT id FROM paintsharp.pdf_pages WHERE document_id = $1 AND page_number = $2",
            params![doc_id, page_num],
        )
        .await?)
}

pub async fn set_page_rotation(db: &DbPool, doc_id: Uuid, page_num: i32, rotation: i32) -> Result<()> {
    db.execute(
        "UPDATE paintsharp.pdf_pages SET rotation = $1
         WHERE document_id = $2 AND page_number = $3",
        params![rotation, doc_id, page_num],
    )
    .await?;
    Ok(())
}

/// Insert used by duplicate: copies a page's geometry and source index.
pub async fn create_page_full(
    db: &DbPool,
    doc_id: Uuid,
    page_number: i32,
    width: f64,
    height: f64,
    rotation: i32,
    source_index: Option<i32>,
) -> Result<Uuid> {
    let id = new_id();
    db.execute(
        "INSERT INTO paintsharp.pdf_pages (id, document_id, page_number, width, height, rotation, source_index)
         VALUES ($1, $2, $3, $4, $5, $6, $7)",
        params![id, doc_id, page_number, width, height, rotation, source_index],
    )
    .await?;
    Ok(id)
}

pub async fn page_count(db: &DbPool, doc_id: Uuid) -> Result<i64> {
    let backend = db.backend();
    let sql = format!(
        "SELECT {} FROM paintsharp.pdf_pages WHERE document_id = $1",
        backend.count_bigint("*")
    );
    Ok(db.fetch_scalar::<i64>(&sql, params![doc_id]).await?)
}

/// Inserts a page after `after`, shifting the later pages and bumping the
/// document's page count. Returns `(page_id, new_page_number)`.
pub async fn add_page(
    db: &DbPool,
    doc_id: Uuid,
    owner: Uuid,
    after: i32,
    width: f64,
    height: f64,
) -> Result<(Uuid, i32)> {
    let mut tx = db.begin().await?;
    tx.execute(
        "UPDATE paintsharp.pdf_pages SET page_number = page_number + 1
         WHERE document_id = $1 AND page_number > $2",
        params![doc_id, after],
    )
    .await?;

    let new_num = after + 1;
    let page_id = new_id();
    tx.execute(
        "INSERT INTO paintsharp.pdf_pages (id, document_id, page_number, width, height)
         VALUES ($1, $2, $3, $4, $5)",
        params![page_id, doc_id, new_num, width, height],
    )
    .await?;

    tx.execute(
        "UPDATE paintsharp.pdf_documents SET page_count = page_count + 1, last_edited_by = $1
         WHERE id = $2",
        params![owner, doc_id],
    )
    .await?;

    tx.commit().await?;
    Ok((page_id, new_num))
}

/// Deletes the given page, closes the gap in numbering and decrements the
/// document's page count. Returns the deleted page's id (if it existed).
pub async fn delete_page(db: &DbPool, doc_id: Uuid, owner: Uuid, page_num: i32) -> Result<Option<Uuid>> {
    let mut tx = db.begin().await?;
    let deleted_id: Option<Uuid> = tx
        .fetch_optional_scalar::<Uuid>(
            "SELECT id FROM paintsharp.pdf_pages WHERE document_id = $1 AND page_number = $2",
            params![doc_id, page_num],
        )
        .await?;
    tx.execute(
        "DELETE FROM paintsharp.pdf_pages WHERE document_id = $1 AND page_number = $2",
        params![doc_id, page_num],
    )
    .await?;
    tx.execute(
        "UPDATE paintsharp.pdf_pages SET page_number = page_number - 1
         WHERE document_id = $1 AND page_number > $2",
        params![doc_id, page_num],
    )
    .await?;
    tx.execute(
        "UPDATE paintsharp.pdf_documents SET page_count = page_count - 1, last_edited_by = $1
         WHERE id = $2",
        params![owner, doc_id],
    )
    .await?;
    tx.commit().await?;
    Ok(deleted_id)
}

/// Reorders pages. `order[new_pos]` is the old (1-based) page number that should
/// land at `new_pos + 1`. Two passes through negative temporaries avoid the
/// UNIQUE(document_id, page_number) conflict.
pub async fn reorder_pages(db: &DbPool, doc_id: Uuid, order: &[i32]) -> Result<()> {
    let mut tx = db.begin().await?;
    for (new_pos, &old_num) in order.iter().enumerate() {
        let tmp = -(new_pos as i32 + 1);
        tx.execute(
            "UPDATE paintsharp.pdf_pages SET page_number = $1
             WHERE document_id = $2 AND page_number = $3",
            params![tmp, doc_id, old_num],
        )
        .await?;
    }
    for new_pos in 0..order.len() {
        let tmp = -(new_pos as i32 + 1);
        tx.execute(
            "UPDATE paintsharp.pdf_pages SET page_number = $1
             WHERE document_id = $2 AND page_number = $3",
            params![(new_pos + 1) as i32, doc_id, tmp],
        )
        .await?;
    }
    tx.commit().await?;
    Ok(())
}

// ── Signatures ────────────────────────────────────────────────────────────────

pub async fn list_signatures(db: &DbPool, owner: Uuid) -> Result<Vec<PdfSignature>> {
    Ok(db
        .fetch_all_as::<PdfSignature>(
            "SELECT * FROM paintsharp.pdf_signatures WHERE owner_id = $1 ORDER BY created_at DESC",
            params![owner],
        )
        .await?)
}

pub async fn create_signature(
    db: &DbPool,
    owner: Uuid,
    name: &str,
    sig_type: &str,
    data: &str,
) -> Result<Uuid> {
    let id = new_id();
    db.execute(
        "INSERT INTO paintsharp.pdf_signatures (id, owner_id, name, sig_type, data)
         VALUES ($1, $2, $3, $4, $5)",
        params![id, owner, name, sig_type, data],
    )
    .await?;
    Ok(id)
}

pub async fn delete_signature(db: &DbPool, id: Uuid, owner: Uuid) -> Result<u64> {
    Ok(db
        .execute(
            "DELETE FROM paintsharp.pdf_signatures WHERE id = $1 AND owner_id = $2",
            params![id, owner],
        )
        .await?)
}
